title = "go-cli-starter"

[app]
name = "cli-starter"
version = "1.0"
usage = "This is a go cli starter"

[app.author]
name = "Aderlx"
email = "aderlx@outlook.com"


[log]
# 日志文件路径
logFilePath = "./logger.log"
# 每个日志文件保存的最大尺寸 单位：M
maxSize = 128
# 日志文件最多保存多少个备份
maxBackups = 30
# 文件最多保存多少天
maxAge = 7
# 是否压缩
compress = true
# 格式 json
formatJson = false